FROM php:8.2-fpm

RUN apt update && docker-php-ext-install pdo_mysql

RUN apt install -y git && apt install -y zip

RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
RUN php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

COPY ./api/docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh

# Install Crontab
RUN apt-get update
RUN apt update && apt-get install -y cron && apt install -y vim

# Add crontab file in the cron directory
#ADD crontab /etc/cron.d/crontab_file
COPY ./crontab_file /etc/cron.d/crontab_file

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontab_file

# Apply cron job
RUN crontab /etc/cron.d/crontab_file

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

WORKDIR /www

COPY ./api .

RUN composer install && chmod 777 -R storage/

EXPOSE 80

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.10.0/wait /wait
RUN chmod +x /wait

RUN /docker-entrypoint.sh

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log

# rodar da pasta raiz -> docker build -t metabase_php -f Dockerfile_php .