version: '3.8'

# pma      running at localhost:8080
# metabase running at localhost:3000
# api      running at localhost:3030/api/v1/test
# swagger  running at localhost:3030/api/v1/documentation

services:
  metabase_jira:
    image: metabase/metabase:latest
    container_name: metabase_jira
    volumes:
      - /dev/urandom:/dev/random:ro
    networks:
      - metabase
    ports:
      - "80:3000"
      - "3000:3000"
    env_file:
      - ./.env
    secrets:
      - db_password
      - db_user
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: metabase_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - metabase
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=mysql.metabase.com
    volumes:
      - ./db-script:/docker-entrypoint-initdb.d
      - ./migration:/migration
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      interval: 10s
      retries: 10

  mysqlinit:
    image: mysql:8.0
    container_name: metabase_init
    networks:
      - metabase
    env_file:
      - ./.env
    volumes:
      - ./migration:/migration
    command: bash -c "sleep 5 && cd /migration && chmod +x init-db.sh && ./init-db.sh"
    depends_on:
      - mysql
    links:
      - mysql

  php:
    image: metabase_php
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: metabase_php_fpm
    command: bash -c "chmod 777 -R storage/ && chmod +x composer.load.sh && ./composer.load.sh && php artisan migrate && php-fpm"
    restart: always
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "9000:9000"
    networks:
      - metabase
    volumes:
      - ./api:/www
      - ./api/storage/logs/cron.log:/var/log/cron.log
      - ./.env:/www/.env
    working_dir: /www
    depends_on:
      - mysql
    links:
      - mysql

  api:
    image: nginx:latest
    container_name: metabase_api_nginx
    restart: always
    ports:
      # - "80:80"
      - "3030:80"
    networks:
      - metabase
        # ipv4_address: 172.20.0.6
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=api.metabase.com
    volumes:
      - ./api:/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
    extra_hosts:
      - "localhost:172.20.0.6"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: metabase_pma
    restart: always
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - metabase
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql

volumes:
  mysql_data:

networks:
  metabase:

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt