version: '3.8'

# pma      running at localhost:8080
# metabase running at localhost:3000
# api      running at localhost:3030/api/v1/test
# swagger  running at localhost:3030/api/v1/documentation

services:
  php:
    image: metabase_php
    build:
      context: .
      dockerfile: ./Dockerfile_php
    container_name: metabase_php_fpm
    command: bash -c "chmod 777 -R storage/ && php artisan migrate && php-fpm"
    restart: always
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "9000:9000"
    networks:
      - metabase
    volumes:
      - ./api:/www
      - ./crontab_file:/etc/cron.d/crontab_file
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    working_dir: /www
    # depends_on:
    #   - mysql
    # links:
    #   - mysql

  api:
    image: nginx:latest
    container_name: metabase_api_nginx
    restart: always
    ports:
      # - "80:80"
      - "3030:80"
    networks:
      - metabase
        # ipv4_address: 172.20.0.6
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.metabase.com
    volumes:
      - ./api:/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    links:
      - php
    depends_on:
      - php
    extra_hosts:
      - "localhost:172.20.0.6"

volumes:
  mysql_data:

networks:
  metabase:

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt