version: '3.8'

services:
  php:
    #image: imagerepo.docker.com/images/metabase-jira:latest
    image: metabase_php
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: metabase_php_fpm
    command: bash -c "chmod 777 -R storage/ && chmod +x composer.load.sh && ./composer.load.sh && php artisan migrate && php-fpm"
    restart: always
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "9000:9000"
    networks:
      - metabase
    volumes:
      - ./api:/www
      - ./api/storage/logs:/var/log
      - ./.env:/www/.env
    working_dir: /www

volumes:
  mysql_data:

networks:
  metabase:

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt